version: '3.8'

services:
  nexus-stream:
    build: 
      context: .
      dockerfile: Dockerfile.txt
    container_name: nexus-stream-app
    ports:
      - "8080:3000"
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./public/uploads:/app/public/uploads
    environment:
      - TZ=Asia/Shanghai
